import 'package:flutter/material.dart';

class Product {
  final String image, title, description;
  final int price, size, id;
  final Color color;
  Product({
    required this.id,
    required this.image,
    required this.title,
    required this.price,
    required this.description,
    required this.size,
    required this.color,
  });
}
List<Product> products = [
  Product(
      id: 1,
      title: "Túi Xanh Lớn",
      price: 234,
      size: 12,
      description: dummyText,
      image: "assets/images/bag_1.png",
      color: Color(0xFF3D82AE)),
  Product(
      id: 2,
      title: "Túi thời tràn vàng ",
      price: 123,
      size: 8,
      description: dummyText,
      image: "assets/images/bag_2.png",
      color: Color(0xFFD3A984)),
  Product(
      id: 3,
      title: "Túi đen thời trang",
      price: 235,
      size: 10,
      description: dummyText,
      image: "assets/images/bag_3.png",
      color: Color(0xFF989493)),
  Product(
      id: 4,
      title: "Túi nâu lớn",
      price: 315,
      size: 11,
      description: dummyText,
      image: "assets/images/bag_4.png",
      color: Color(0xFFE6B398)),
  Product(
      id: 5,
      title: "Túi hồng thời trang",
      price: 999,
      size: 12,
      description: dummyText,
      image: "assets/images/bag_5.png",
      color: Color(0xFFFB7883)),
  Product(
    id: 7,
    title: "Túi đen",
    price: 65,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_6.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
      id: 8,
      title: "Túi thời trang vàng ",
      price: 123,
      size: 8,
      description: dummyText,
      image: "assets/images/bag_2.png",
      color: Color(0xFFD3A984)),
  Product(
    id: 9,
    title: "Túi đen",
    price: 65,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_6.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
      id: 10,
      title: "Túi nâu lớn",
      price: 315,
      size: 11,
      description: dummyText,
      image: "assets/images/bag_4.png",
      color: Color(0xFFE6B398)),
  Product(
    id: 11,
    title: "Túi đen",
    price: 65,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_6.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 12,
    title: "Túi đen",
    price: 65,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_6.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 13,
    title: "Túi đen",
    price: 65,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_6.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 14,
    title: "Túi đen",
    price: 65,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_6.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 15,
    title: "Túi Dom",
    price: 135,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 16,
    title: "Túi Dom",
    price: 135,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 17,
    title: "Túi Dom",
    price: 135,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 18,
    title: "Túi Dom",
    price: 135,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 19,
    title: "Túi Dom",
    price: 135,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 20,
    title: "Túi Dom",
    price: 135,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 21,
    title: "Túi Dom",
    price: 135,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 22,
    title: "Túi Dom",
    price: 135,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 23,
    title: "Túi Dom",
    price: 135,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 24,
    title: "Túi Dom",
    price: 135,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 25,
    title: "Túi Dom",
    price: 135,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 26,
    title: "Túi Dom",
    price: 135,
    size: 27,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 28,
    title: "Túi Dom",
    price: 135,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 29,
    title: "Túi Dom",
    price: 135,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFAEAEAE),
  ),
  Product(
    id: 30,
    title: "Túi Dom",
    price: 135,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFAEAEAE),
  ),
];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";

